### ISSUE TITLE
Python install fails

### ISSUE THREAD

**Issue by sjvrijn** [usnistgov/CEGO#1]
The instructions `python setup.py install` currently fails for Python2.7, 3.6 and 3.7 under Ubuntu 18.04. When trying `pip install .` instead, a message `Failed building wheel for PyCEGO` pops up as part of the output.

Full error output from `python setup.py install` (3.7):

    sjvrijn:/src/CEGO$ python setup.py install
    running install
    running bdist_egg
    running egg_info
    writing PyCEGO.egg-info/PKG-INFO
    writing dependency_links to PyCEGO.egg-info/dependency_links.txt
    writing top-level names to PyCEGO.egg-info/top_level.txt
    reading manifest file 'PyCEGO.egg-info/SOURCES.txt'
    writing manifest file 'PyCEGO.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_ext
    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /src/CEGO/venv/bin/python (found version "3.7.2") 
    -- Found PythonLibs: /home/sander/local/lib/libpython3.7m.a
    -- pybind11 v2.2.dev0
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- Performing Test HAS_CPP11_FLAG
    -- Performing Test HAS_CPP11_FLAG - Success
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    CMake Error at CMakeLists.txt:21 (target_link_libraries):
      The keyword signature for target_link_libraries has already been used with
      the target "PyCEGO".  All uses of target_link_libraries with a target must
      be either all-keyword or all-plain.

      The uses of the keyword signature are here:

       * externals/pybind11/tools/pybind11Tools.cmake:107 (target_link_libraries)

    Call Stack (most recent call first):
      CMakeLists.txt:32 (add_nix_libraries)
      CMakeLists.txt:40 (attach_includes)

    -- Configuring incomplete, errors occurred!
    See also "/src/CEGO/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    See also "/src/CEGO/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "setup.py", line 70, in <module>
        zip_safe=False,
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/sander/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/sander/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/sander/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
        self.do_egg_install()
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
        self.run_command('bdist_egg')
      File "/home/sander/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sander/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "/home/sander/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sander/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/src/CEGO/venv/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/home/sander/local/lib/python3.7/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/home/sander/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sander/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 34, in run
        self.build_extension(ext)
      File "setup.py", line 58, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/sander/local/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/src/CEGO', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/src/CEGO/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/src/CEGO/venv/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

This seems to extend to installs through the [binder badge link](https://mybinder.org/v2/gh/usnistgov/CEGO/master) too:

    [...]
    Command "/srv/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp
    /pip-req-build-h7la7icm/setup.py';f=getattr(tokenize, 'open', open)(__file__);co
    de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')
    )" install --record /tmp/pip-record-5otxyiy3/install-record.txt --single-version
    -externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-h7
    la7icm/

    CondaValueError: pip returned an error

    Removing intermediate container e0dd8f91272f
    The command '/bin/sh -c conda env update -n root -f "environment.yml" && conda c
    lean -tipsy && conda list -n root' returned a non-zero code: 1

**Comment by ianhbell** [comment]
Thanks for the report.  I "fixed" some issues, but I guess I don't have the most up-to-date cmake on my windows box, as I didn't run into this problem.  I now force Travis to run the ``python setup.py build`` to ensure the python builds are ok, and I'm working through another Travis issue that only now is biting me.

**Comment by ianhbell** [comment]
*Phew* I think I have binder and TravisCI builds running again.
