### ISSUE TITLE
An error occurred while testing the example

### ISSUE THREAD

**Issue by tcxiaoma** [usnistgov/CEGO#3]
The code was downloaded and compiled normally. The examples in Notebooks can not work correctly when using Jupyter.In order to eliminate the possible missing files caused by the network, I redownloaded and compiled several times, but the problem still appeared.
The versions of the software or module in my computer were listed,
        python:3.8.8
        VS:Visual Studio 2019 Community
        numpy:1.19.2

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-2d57a4dccd9f> in <module>
     14 VTR = 1e-10 # Value to reach as acceptable optimization run
     15 for counter in range(1000):
---> 16     layers.do_generation()
     17     cost, coeffs = layers.get_best()
     18     if counter % 50 == 0:

RuntimeError: NumPy type info missing for struct CEGO::numberish

**Comment by ianhbell** [comment]
Confirmed.  It seems that numpy has added some requirements on numerical types stored in numpy arrays, which is unfortunate.  I'll have to dig into this one.

Thanks for the report.

**Comment by tcxiaoma** [comment]
Many thanks.

**Comment by ianhbell** [comment]
This bug is a real tricky one. There have been some changes to numpy/Eigen/pybind11 integration, and I can't quite make out whether this should have ever worked before.  So I may need to make some major changes.  In the meantime, please consider to use the Double type rather than Numberish (a floating point and integer datatype).  That should still work fine.

**Comment by ianhbell** [comment]
See https://github.com/pybind/pybind11/issues/2905

**Comment by tcxiaoma** [comment]
I tried to lower the version of some of my runtime environments(python,eigen,pybind11 and numpy), but it didn't seem to work.I can't seem to find the right combination of old versions.

**Comment by ianhbell** [comment]
Yeah, that's a good start.  Do you need mixed integer and double types?  

The binder instance was still working not too long ago, so if you used an older version of Eigen and python 3.6, that might work.

**Comment by ianhbell** [comment]
FWIW, I got CEGO version 1.0 from the release to work in python 3.7. This was my conda environment:
```
name: CEGO2
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37h2bbff1b_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py37haa95532_0
  - cffi=1.14.5=py37hcd4344a_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - icu=58.2=ha925a31_3
  - importlib-metadata=3.7.3=py37haa95532_1
  - importlib_metadata=3.7.3=hd3eb1b0_1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.21.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py37_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.3.0=py37h46781fe_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.2.0=py37haa95532_0
  - numpy=1.19.2=py37hadc3359_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py37haa95532_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py37haa95532_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - python=3.7.0=hea74fb7_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=20.0.0=py37hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37haa95532_0
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py37haa95532_0
  - sqlite=3.35.1=h2bbff1b_0
  - terminado=0.9.3=py37haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - pycego==1.0.0
 ```

**Comment by tcxiaoma** [comment]
I've been testing the old version combination without success. The good news came just in time.  I'll set up right away according to your environment, thank you very much. Your last published abstract mentioned that fitting of eos is related to MINLP problems, so mixed types are still needed.

**Comment by ianhbell** [comment]
To be honest, the approach in CEGO has given me only middling success with fitting mixture models (similar problem to fitting EOS) as mixed-integer problems.  Not for a lack of trying, that is for sure.

**Comment by tcxiaoma** [comment]
I have seen a module called Helmet(url: https://idaes-pse.readthedocs.io/en/1.3.0/apps/helmet.html), which provide a framework for regressing eos. It seems to use GAMS' BARON solver for MINLP problems.

**Comment by ianhbell** [comment]
Interesting - you need to have GAMS for that, unfortunately.  But worth looking into.  Can you shoot me an email at ian.bell@nist.gov ?

**Comment by tcxiaoma** [comment]
With pleasure.

**Comment by ianhbell** [comment]
I finally fixed this...  Version 1.1.0 allows for integers and doubles again...  It took me a couple of tries to figure out the right approach, but I think I got there eventually.
